### ISSUE TITLE
add setup instructions to readme

### ISSUE THREAD

**Issue by lassediercks** [s0enke/gapps-teamboard#10] opened 2015-08-17 14:27 UTC
In order to contribute, I'd like to know how to run this locally. Maybe even with democontent

**Comment by s0enke** [comment] 2015-08-17 19:00
Hi @lassediercks 

Please find a first draft of instructions here: https://github.com/s0enke/gapps-teamboard/pull/11 - please report any bugs or obstacles in #1 or #11 !

Duplicate of #1

**Closed as completed by s0enke** 2015-08-17 19:00 UTC
